#cloud-config
autoinstall:
  version: 1
  locale: zh_CN
  keyboard:
    layout: cn
  identity:
    hostname: ubuntu-desktop
    password: "$6$rounds=4096$saltsalt$9ynlPz9tHHGh6YgXqDB8Bz.k8GQjyZeKKsR5K8Sg0.pYqx5UGxwm9RpZthEZjm3FvRqE8EXyLEV6Q/2GYB/Qj1"
    username: root
    realname: Root User
  storage:
    layout:
      name: direct
    swap:
      size: 0
  packages:
    - vim
    - curl
    - wget
    - net-tools
    - htop
    - open-vm-tools
    - git
    - ca-certificates
    - apt-transport-https
    - lsof
    - htop
    - iotop
    - iftop
    - sysstat
    - dstat
    - telnet
    - nmap
    - tcpdump
    - traceroute
    - mtr
    - iperf3
    - iproute2
    - dnsutils
    - iputils-ping
    - zip
    - unzip
    - tar
    - gzip
    - bzip2
    - rsync
    - screen
    - tmux
    - tree
    - mc
    - dos2unix
    - jq
    - make
    - gcc
    - build-essential
    - python3-pip
    - bash-completion
  updates: security
  timezone: Asia/Shanghai
  user-data:
    disable_root: false
    package_upgrade: true
  late-commands:
    # SSH配置 - 无安全限制
    - |
      cat > /target/etc/ssh/sshd_config << EOF
      Port 22
      ListenAddress 0.0.0.0
      PermitRootLogin yes
      PermitEmptyPasswords yes
      PubkeyAuthentication no
      PasswordAuthentication yes
      ChallengeResponseAuthentication no
      HostbasedAuthentication no
      GSSAPIAuthentication no
      UsePAM no
      AllowAgentForwarding yes
      AllowTcpForwarding yes
      X11Forwarding yes
      PrintMotd no
      TCPKeepAlive yes
      ClientAliveInterval 60
      ClientAliveCountMax 3
      UseDNS no
      MaxAuthTries 10
      MaxSessions 10
      AcceptEnv LANG LC_*
      Subsystem sftp /usr/lib/openssh/sftp-server
      EOF
    # 修改软件源为中国CDN
    - |
      cat > /target/etc/apt/sources.list << EOF
      deb https://cn.archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
      deb https://cn.archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse
      deb https://cn.archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
      deb https://cn.archive.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
      EOF
    # 安装和配置 VMware Tools
    - curtin in-target --target=/target -- apt-get install -y open-vm-tools open-vm-tools-desktop
    - curtin in-target --target=/target -- systemctl enable vmtoolsd
    - curtin in-target --target=/target -- systemctl start vmtoolsd
    # 禁用初始设置向导
    - touch /target/etc/cloud/cloud-init.disabled
