#cloud-config
autoinstall:
  version: 1
  locale: zh_CN
  keyboard:
    layout: cn
  identity:
    hostname: ubuntu-server
    password: "$6$rounds=4096$saltsalt$9ynlPz9tHHGh6YgXqDB8Bz.k8GQjyZeKKsR5K8Sg0.pYqx5UGxwm9RpZthEZjm3FvRqE8EXyLEV6Q/2GYB/Qj1"
    username: root
    realname: Root User
  storage:
    layout:
      name: direct
    swap:
      size: 0
  network:
    network:
      version: 2
      ethernets:
        eth0:
          dhcp4: false
          addresses: [192.168.31.200/24]
          gateway4: 192.168.31.120
          nameservers:
            addresses: [8.8.8.8, 114.114.114.114]
  ssh:
    install-server: true
    allow-pw: true
  packages:
    - openssh-server
    - vim
    - curl
    - wget
    - net-tools
    - htop
  updates: security
  timezone: Asia/Shanghai
  user-data:
    disable_root: false
    package_upgrade: true
  late-commands:
    - sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /target/etc/ssh/sshd_config
    - sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /target/etc/ssh/sshd_config
    - sed -i 's/PubkeyAuthentication yes/PubkeyAuthentication no/' /target/etc/ssh/sshd_config
