#cloud-config
autoinstall:
  version: 1
  locale: zh_CN
  keyboard:
    layout: cn
  identity:
    hostname: ubuntu-desktop
    password: "$6$rounds=4096$saltsalt$9ynlPz9tHHGh6YgXqDB8Bz.k8GQjyZeKKsR5K8Sg0.pYqx5UGxwm9RpZthEZjm3FvRqE8EXyLEV6Q/2GYB/Qj1"
    username: root
    realname: Root User
  storage:
    layout:
      name: direct
    swap:
      size: 0
  packages:
    - vim
    - curl
    - wget
    - net-tools
    - htop
    - open-vm-tools
    - git
    - zip
    - unzip
    - tar
    - rsync
    - screen
    - tmux
    - iftop
    - iotop
    - nmap
    - tcpdump
    - lsof
    - tree
    - dos2unix
    - bash-completion
    - dnsutils
    - iputils-ping
    - telnet
  updates: security
  timezone: Asia/Shanghai
  user-data:
    disable_root: false
    package_upgrade: true
  late-commands:
    # 允许root登录
    - sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /target/etc/ssh/sshd_config
    - sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /target/etc/ssh/sshd_config
    - sed -i 's/PubkeyAuthentication yes/PubkeyAuthentication no/' /target/etc/ssh/sshd_config
    # 修改软件源
    - |
      cat > /target/etc/apt/sources.list << EOF
      deb https://cn.archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
      deb https://cn.archive.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
      deb https://cn.archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse
      deb https://cn.archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
      EOF
    # 安装必要的包
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get install -y ca-certificates apt-transport-https
    # 彻底禁用桌面初始设置
    - curtin in-target --target=/target -- apt-get purge -y gnome-initial-setup ubuntu-desktop-bootstrap
    - rm -f /target/usr/lib/gnome-initial-setup/gnome-initial-setup
    - rm -f /target/usr/share/gnome-initial-setup/
    - mkdir -p /target/etc/skel/.config
    - touch /target/etc/skel/.config/gnome-initial-setup-done
    - touch /target/root/.config/gnome-initial-setup-done
    - sed -i 's/InitialSetupEnable=true/InitialSetupEnable=false/' /target/etc/gdm3/custom.conf
    - curtin in-target --target=/target -- systemctl disable gnome-initial-setup-first-login.service
    - curtin in-target --target=/target -- systemctl mask gnome-initial-setup-first-login.service
    - touch /target/etc/cloud/cloud-init.disabled
    # 禁用错误报告
    - curtin in-target --target=/target -- systemctl disable apport.service
    - curtin in-target --target=/target -- systemctl mask apport.service
    - sed -i 's/enabled=1/enabled=0/' /target/etc/default/apport
    # 禁用崩溃报告
    - curtin in-target --target=/target -- apt-get remove -y whoopsie
    - curtin in-target --target=/target -- systemctl disable whoopsie.service
    - curtin in-target --target=/target -- systemctl mask whoopsie.service
    # 配置错误报告保存到指定目录
    - mkdir -p /target/home/ubuntu/crash-reports
    - chmod 777 /target/home/ubuntu/crash-reports
    - |
      cat > /target/etc/default/apport << EOF
      enabled=1
      report_dir=/home/ubuntu/crash-reports
      EOF
    - |
      cat > /target/etc/apport/crashdb.conf << EOF
      default:
          problem_types: ['Bug', 'Package', 'Crash']
          output_dir: /home/ubuntu/crash-reports
          db_file: /home/ubuntu/crash-reports/apport.db
      EOF
