#cloud-config
autoinstall:
  version: 1
  early-commands:
    - echo "这里的命令会在安装开始前执行"
    - date >> /tmp/install_time.log
  locale: zh_CN
  keyboard:
    layout: cn
  identity:
    hostname: ubuntu-server
    password: "$6$rounds=4096$saltsalt$9ynlPz9tHHGh6YgXqDB8Bz.k8GQjyZeKKsR5K8Sg0.pYqx5UGxwm9RpZthEZjm3FvRqE8EXyLEV6Q/2GYB/Qj1"
    username: root
    realname: Root User
  storage:
    layout:
      name: direct
    swap:
      size: 0
  network:
    network:
      version: 2
      ethernets:
        eth0:
          dhcp4: false
          addresses: [192.168.31.200/24]
          gateway4: 192.168.31.120
          nameservers:
            addresses: [8.8.8.8, 114.114.114.114]
  ssh:
    install-server: true
    allow-pw: true
  packages:
    - openssh-server
    - vim
    - curl
    - wget
    - net-tools
    - htop
    - open-vm-tools
  updates: security
  timezone: Asia/Shanghai
  user-data:
    disable_root: false
    package_upgrade: true
  late-commands:
    - sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /target/etc/ssh/sshd_config
    - sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /target/etc/ssh/sshd_config
    - sed -i 's/PubkeyAuthentication yes/PubkeyAuthentication no/' /target/etc/ssh/sshd_config
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get install -y open-vm-tools
    # 禁止创建新用户
    - sed -i 's/^USERGROUPS_ENAB.*/USERGROUPS_ENAB no/' /target/etc/login.defs
    - sed -i 's/^CREATE_HOME.*/CREATE_HOME no/' /target/etc/login.defs
    # 创建一个脚本来恢复设置
    - |
      echo '#!/bin/bash
      sed -i "s/^USERGROUPS_ENAB.*/USERGROUPS_ENAB yes/" /etc/login.defs
      sed -i "s/^CREATE_HOME.*/CREATE_HOME yes/" /etc/login.defs
      rm -f /etc/cron.d/restore-user-creation
      ' > /target/usr/local/sbin/restore-user-creation.sh
    - chmod +x /target/usr/local/sbin/restore-user-creation.sh
    # 创建定时任务，3小时后恢复
    - echo "0 */3 * * * root /usr/local/sbin/restore-user-creation.sh" > /target/etc/cron.d/restore-user-creation
    - chmod 644 /target/etc/cron.d/restore-user-creation
